"""add article metadata

Revision ID: 67a862eb709e
Revises: 799b811711fb
Create Date: 2026-01-21 14:21:14.154118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a862eb709e'
down_revision = '799b811711fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_articles', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('saved_articles', sa.Column('author', sa.String(), nullable=True))
    op.add_column('saved_articles', sa.Column('published_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_articles', 'published_at')
    op.drop_column('saved_articles', 'author')
    op.drop_column('saved_articles', 'thumbnail_url')
    # ### end Alembic commands ###
