"""add summary to cache

Revision ID: 7ab94e516bfc
Revises: 67a862eb709e
Create Date: 2026-01-21 16:04:38.748536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab94e516bfc'
down_revision = '67a862eb709e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_cache', sa.Column('summary', sa.String(), nullable=True))
    # op.drop_index(op.f('saved_articles_user_id_idx'), table_name='saved_articles')
    # op.drop_index(op.f('usage_logs_user_id_idx'), table_name='usage_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('usage_logs_user_id_idx'), 'usage_logs', ['user_id'], unique=False)
    op.create_index(op.f('saved_articles_user_id_idx'), 'saved_articles', ['user_id'], unique=False)
    op.drop_column('content_cache', 'summary')
    # ### end Alembic commands ###
