"""add action to usage_logs

Revision ID: 8d106fbde0bf
Revises: 35f650de9e2b
Create Date: 2026-01-21 13:33:52.317186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d106fbde0bf'
down_revision = '35f650de9e2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_logs', sa.Column('action', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_logs', 'action')
    # ### end Alembic commands ###
